spring.application.name=quizservice

spring.datasource.url=jdbc:postgresql://localhost:5434/quizservice_db
spring.datasource.username=quizuser
spring.datasource.password=quizpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration